### ISSUE TITLE
HTML stream problem with stdin (Node v. 8.11.3 on Windows 10 Ubuntu/WSL)

### ISSUE THREAD

**Issue by jasonsbarr** [workshopper/stream-adventure#214] opened 2018-07-19 00:59 UTC
Hello,

I am trying to do the HTML stream in exercise 10 using the trumpet and through2 packages.

I came up with a solution very much like the one the program suggests but got the following error:

```
internal/process/stdio.js:90
        throw new errors.Error('ERR_UNKNOWN_STDIN_TYPE');
        ^

Error [ERR_UNKNOWN_STDIN_TYPE]: Unknown stdin file type
    at process.getStdin [as stdin] (internal/process/stdio.js:90:15)
    at Object.<anonymous> (/mnt/c/Users/jason/Tutorials/NodeSchool/stream-adventure/10_HTML_Stream/html.js:11:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

When I tried copying and pasting your exact solution I got the same error. I tried rewriting the code to process the stream directly without through the trumpet stream's `on('data'...` method but got the same error. So it seems the issue has to do with how Node receives stdin, not with my code.

I'm using stream-adventure 4.1.1 with Node 8.11.3 and the latest versions of NPM and the other dependencies with Windows 10's Ubuntu/WSL Bash shell.

It seems possible, perhaps even likely that the issue is related to Windows 10, as during my attempts to Google a solution I've found several references to problems with Windows and Node getting input from stdin but this is the first time I've had an issue with it through the whole course.

Any ideas on how to fix this?

**Comment by dasalazar1** [comment] 2018-09-04 12:55
Hi Jason, did you ever find a solution to this? I am getting the same error in the same situation. Win 10/WSL/Node 8.11.4. Node isn't installed in Windows, only in the WSL.

**Comment by dasalazar1** [comment] 2018-09-07 16:41
Looks like this was fixed in an insider build. Build 17713. Insider program with settings 'Active Development', and pace 'Slow' will get you to build 17744. Confirmed test goes through now.

https://github.com/Microsoft/WSL/issues/1774

**Comment by ccarruitero** [comment] 2020-04-24 20:38
Closing since seems the problem with WSL was solved

**Closed by ccarruitero** 2020-04-24 20:38 UTC
